### ISSUE TITLE
config after_configuration fails with middleman 4.1

### ISSUE THREAD

**Issue by handylearn** [paperdigits/middleman-foundation-6#2]
I have upgraded a site from middleman 3.4 to 4.1.2.  Now when I start the middleman server, I get the following error:

> config.rb:61:in `block in evaluate_configuration!': undefined local variable or method`sprockets' for #Middleman::ConfigContext:0x007ff56147f1e0 (NameError)

This happens in the following lines of config.rb

```
# Add bower's directory to sprockets asset path
after_configuration do
  @bower_config = JSON.parse(IO.read("#{root}/.bowerrc"))
  sprockets.append_path File.join "#{root}", @bower_config["directory"]
end
```

**Comment by paperdigits** [comment]
I haven't tried to update to v4 yet, so I've yet to test this template against it. 

What does your Gemfile look like? From the [middleman v4 update page](https://middlemanapp.com/basics/upgrade-v4/):

Removed sprockets, add `gem "middleman-sprockets", "~> 4.0.0.rc"` to Gemfile

**Comment by handylearn** [comment]
Thanks, 
I now managed to let it work with middleman 4.1.2.
my new Gemfile contains:
gem "middleman", "~>4.1.2"
gem "middleman-blog", "~>4.0"
gem "middleman-compass"
gem "middleman-sprockets", "~> 4.0.0.rc"
gem 'middleman-autoprefixer'
gem "middleman-livereload", "~> 3.4"

Another upgrade issue was in the with title tag inside the layout template, 
because of this change "Remove page template local. Use current_resource instead."

**Comment by paperdigits** [comment]
Thanks for letting me know! Was there anything else needed to get it running? I'd like to update to 4.0 eventually too.

**Comment by handylearn** [comment]
foundation version itself needed some update in bower.json, otherwise it displays deprecation warnings in sass files. I have created a pull request with my changes.

**Comment by paperdigits** [comment]
The branch `mm4` makes this template compatible with Middleman 4. When all the gems are no longer RC, I'll merge `mm4` onto `master`.

**Comment by asecondwill** [comment]
I had to add `activate :sprockets` to the top of config.rb to get past the sprockets error.  and like handylearn change title in layout to `current_resource.data.title`

**Comment by paperdigits** [comment]
@asecondwill thanks, 221a9e5d667744ed51db971b9e7bc3ee4de03238 fixes that issue.
